#!/bin/sh
set -eu

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<SQL
CREATE ROLE financas_owner LOGIN PASSWORD '${OWNER_DB_PASSWORD}';
CREATE ROLE financas_app LOGIN PASSWORD '${APP_DB_PASSWORD}';

ALTER DATABASE ${POSTGRES_DB} OWNER TO financas_owner;
ALTER SCHEMA public OWNER TO financas_owner;
REVOKE ALL ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO financas_app;

ALTER DEFAULT PRIVILEGES FOR ROLE financas_owner IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO financas_app;
ALTER DEFAULT PRIVILEGES FOR ROLE financas_owner IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO financas_app;
ALTER DEFAULT PRIVILEGES FOR ROLE financas_owner IN SCHEMA public
  GRANT EXECUTE ON FUNCTIONS TO financas_app;
SQL
